name: auto-assign author
on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Assign author
        run: |
            echo "Assigning author to PR"
            echo "PR author: ${{ github.event.pull_request.user.login }}"
            echo "PR number: ${{ github.event.pull_request.number }}"
            echo "Assigning author to PR"
            gh api --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
              -f "assignees[]=${{ github.event.pull_request.user.login }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
