name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/test-go@master

  lint-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/lint-go@master

  lint-prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/prettier@master
        with:
          pat: ${{ secrets.ACTION_PAT }}

  report-codecov:
    runs-on: ubuntu-latest
    needs: [test, lint-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/codecov@master
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  report-grc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    needs: [test, lint-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/go-report-card@master
        if: github.ref == 'refs/heads/master' && success()
