name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/test-go@master

  detect-modules:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  lint-go:
    needs: [detect-modules]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/lint-go@master
        with:
          working-directory: ${{ matrix.modules }}

  lint-prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/prettier@master
        with:
          pat: ${{ secrets.ACTION_PAT }}

  report-codecov:
    runs-on: ubuntu-latest
    needs: [test, lint-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/codecov@master
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  report-grc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    needs: [test, lint-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/go-report-card@master
        if: github.ref == 'refs/heads/master' && success()
